concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.sha }}
jobs:
  build:
    needs:
    - checks
    strategy:
      matrix:
        etcd:
        - gcr.io/etcd-development/etcd:v3.5.10
        - gcr.io/etcd-development/etcd:v3.4.27
        java-version:
        - 11
        - 17
        - 21
    uses: ./.github/workflows/build.yml
    with:
      etcdImage: ${{ matrix.etcd }}
      javaVersion: ${{ matrix.java-version }}
  checks:
    uses: ./.github/workflows/checks.yml
  publish:
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set Up Java
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Collect Info
      run: './gradlew currentVersion

        '
    - continue-on-error: true
      env:
        NEXUS_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        NEXUS_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      if: github.event_name != 'schedule'
      name: Publish Snapshot
      run: './gradlew publishToSonatype -Prelease.forceSnapshot

        '
name: Build and Publish (Snapshot)
on:
  repository_dispatch:
    types: trigger-ga___build-main.yml
